module ErrorEnum
	ILLEGAL_EMAIL = -1
	EMAIL_ACTIVATED = -2
	EMAIL_NOT_ACTIVATED = -3
	EMAIL_NOT_EXIST = -4
	ACTIVATE_EXPIRED = -5
	WRONG_PASSWORD_CONFIRMATION = -10
	WRONG_PASSWORD = -11
	EXIST = -20
	NOT_EXIST = -21
	UNAUTHORIZED = -22
	SURVEY_NOT_EXIST = -30
	QUESTION_NOT_EXIST = -31
	WRONG_QUESTION_TYPE = -32
	OVERFLOW = -33
end
