module QuestionTypeEnum
	CHOICE_QUESTION = 0
	MATRIX_CHOICE_QUESTION = 1
	TEXT_BLANK_QUESTION = 2
	NUMBER_BLANK_QUESTION = 3
	EMAIL_BLANK_QUESTION = 4
	PHONE_BLANK_QUESTION = 5
	TIME_BLANK_QUESTION = 6
	ADDRESS_BLANK_QUESTION = 7
	BLANK_QUESTION = 8
	MATRIX_BLANK_QUESTION = 9
	CONST_SUM_QUESTION = 10
	SORT_QUESTION = 11
	RANK_QUESTION = 12
	PARAGRAPH = 13
	FILE_QUESTION = 14
	TABLE_QUESTION = 15
end
