development:
  faye_server: "http://127.0.0.1:9393/faye"
  faye_token: "oopsdata@2014"

staging:
  faye_server: "http://127.0.0.1:9393/faye"
  faye_token: "oopsdata@2014"

production:
  faye_server: "http://www.wenjuanba.com:9393/faye"
  faye_token: "oopsdata@2014"
