development:
  host: localhost
  database: oops_data_development_from_oliver

test:
  host: localhost
  database: oops_data_test

# set these environment variables on your prod server
staging:
  host: localhost
  port: 27017
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: oops_data_staging
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

production:
  host: localhost
  port: 27017
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: oops_data_development
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
