development:

  host: localhost
  # database: oops_data_development_from_oliver

  # host: 192.168.1.100

  port: 27017
  username: <%= "oopsdata_d" %>
  password: <%= "tsinghua" %>
  database: oops_data_development

test:
  host: localhost
  database: oops_data_test

# set these environment variables on your prod server
staging:
  host: localhost
  port: 27017
  username: <%= "oopsdata_s" %>
  password: <%= "tsinghua" %>
  database: oops_data_staging
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

production:
  host: localhost
  port: 27017
  username: <%= "oopsdata_p" %>
  password: <%= "tsinghua" %>
  database: oops_data_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
