development:
# host: 192.168.1.103
  host: localhost
  database: oops_data_development

test:
  host: localhost
  database: oops_data_test

# set these environment variables on your prod server
production:
  host: localhost
  port: 27017
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: oops_data_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
