production:
  words_per_second: 5
  login_count_threshold: 1000
  activate_expiration_time: 86400
  password_expiration_time: 86400
  cache_key_prefix: "oopsdata_"
  redis_hostname: "orange02"
  renren_app_id: "242457"
  renren_app_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_app_secret: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://www.wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "801426466"
  tecent_app_secret: "bc29ec016529bb4085689d378c3979be"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"
  alipay_app_key: "2088901873811631"
  alipay_app_secret: "4ooqffbbyw433itxemcsg2js508o0gqr"
  alipay_redirect_uri: "http://127.0.0.1:8000/connects/alipay"  
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://test.oopsdata.com/qihu_connect"
demo:
  words_per_second: 5
  login_count_threshold: 1000
  activate_expiration_time: 86400
  password_expiration_time: 86400
  cache_key_prefix: "oopsdata_"
  redis_hostname: "orange02"
  renren_app_id: "242457"
  renren_app_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_app_secret: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://www.wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "801426466"
  tecent_app_secret: "bc29ec016529bb4085689d378c3979be"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"
  alipay_app_key: "2088901873811631"
  alipay_app_secret: "4ooqffbbyw433itxemcsg2js508o0gqr"
  alipay_redirect_uri: "http://127.0.0.1:8000/connects/alipay"  
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://test.oopsdata.com/qihu_connect"
staging:
  words_per_second: 5
  login_count_threshold: 1000
  activate_expiration_time: 86400
  password_expiration_time: 86400
  cache_key_prefix: "oopsdata_"
  redis_hostname: "orange02"
  renren_app_id: "242457"
  renren_app_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_app_secret: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://www.wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "801426466"
  tecent_app_secret: "bc29ec016529bb4085689d378c3979be"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"
  alipay_app_key: "2088901873811631"
  alipay_app_secret: "4ooqffbbyw433itxemcsg2js508o0gqr"
  alipay_redirect_uri: "http://127.0.0.1:8000/connects/alipay"  
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://test.oopsdata.com/qihu_connect"
development:
  words_per_second: 5
  login_count_threshold: 100
  activate_expiration_time: 3600
  password_expiration_time: 3600
  cache_key_prefix: "oopsdata_"
  redis_hostname: "localhost"
  renren_app_id: "242457"
  renren_app_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_app_secret: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://www.wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "801426466"
  tecent_app_secret: "bc29ec016529bb4085689d378c3979be"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"
  alipay_app_key: "2088901873811631"
  alipay_app_secret: "4ooqffbbyw433itxemcsg2js508o0gqr"
  alipay_redirect_uri: "http://127.0.0.1:8000/connects/alipay"  
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://test.oopsdata.com/qihu_connect"
test:
  words_per_second: 5
  login_count_threshold: 100000
  activate_expiration_time: 3600
  password_expiration_time: 3600
  cache_key_prefix: "oopsdata_"
  redis_hostname: "localhost"
  renren_app_id: "242457"
  renren_app_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_app_secret: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://www.wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "801426466"
  tecent_app_secret: "bc29ec016529bb4085689d378c3979be"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"
  alipay_app_key: "2088901873811631"
  alipay_app_secret: "4ooqffbbyw433itxemcsg2js508o0gqr"
  alipay_redirect_uri: "http://127.0.0.1:8000/connects/alipay"  
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://test.oopsdata.com/qihu_connect"

question_default_settings:
  content: "请在此输入问题标题"
  note: ""

login_keep_time: 86400 # 1.days.to_i
