production:
  words_per_second: 5
  login_count_threshold: 1000
  activate_expiration_time: 86400
  password_expiration_time: 86400
  cache_key_prefix: "oopsdata_"
  redis_hostname: "orange02"
  renren_app_id: "194585"
  renren_api_key: "aa0e45712a7a4960af981ea3f6918b86"
  renren_secret_key: "b2490c767d264f848a3ef026aadcace0"
  renren_redirect_uri: "http://quill.oopsdata.com/renren_connect"
  sina_app_key: "2963346595"
  sina_app_secret: "cbe13ee9c88aa72f992d45a0f8d7edd7"
  sina_redirect_uri: "http://quill.netinsight.cn/sina_connect"
  qq_app_id: "100271825"
  qq_app_key: "31d510c1ce2265b8e38d5ab6dbcea119"
  qq_redirect_uri: "http://quill.oopsdata.com/qq_connect"
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://quill.oopsdata.com/google_connect"
  qihu_app_id: "102205843"
  qihu_app_key: "ca6d278b690138f21cf31ea6fd3f6e2e"
  qihu_app_secret: "25e635ca1c06b32ef02f1fbfa996c74d"
  qihu_redirect_uri: "http://quill.oopsdata.com/qihu_connect"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"
staging:
  words_per_second: 5
  login_count_threshold: 1000
  activate_expiration_time: 86400
  password_expiration_time: 86400
  cache_key_prefix: "oopsdata_"
  redis_hostname: "orange02"
  renren_app_id: "194585"
  renren_api_key: "aa0e45712a7a4960af981ea3f6918b86"
  renren_secret_key: "b2490c767d264f848a3ef026aadcace0"
  renren_redirect_uri: "http://quill.oopsdata.com/renren_connect"
  sina_app_key: "2963346595"
  sina_app_secret: "cbe13ee9c88aa72f992d45a0f8d7edd7"
  sina_redirect_uri: "http://quill.netinsight.cn/sina_connect"
  qq_app_id: "100271825"
  qq_app_key: "31d510c1ce2265b8e38d5ab6dbcea119"
  qq_redirect_uri: "http://quill.oopsdata.com/qq_connect"
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://quill.oopsdata.com/google_connect"
  qihu_app_id: "102205843"
  qihu_app_key: "ca6d278b690138f21cf31ea6fd3f6e2e"
  qihu_app_secret: "25e635ca1c06b32ef02f1fbfa996c74d"
  qihu_redirect_uri: "http://quill.oopsdata.com/qihu_connect"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"
development:
  words_per_second: 5
  login_count_threshold: 100
  activate_expiration_time: 3600
  password_expiration_time: 3600
  cache_key_prefix: "oopsdata_"
  redis_hostname: "localhost"
  renren_app_id: "194585"
  renren_api_key: "aa0e45712a7a4960af981ea3f6918b86"
  renren_secret_key: "b2490c767d264f848a3ef026aadcace0"
  renren_redirect_uri: "http://quillme.oopsdata.com:3000/connects/renren"
  sina_app_key: "2963346595"
  sina_app_secret: "cbe13ee9c88aa72f992d45a0f8d7edd7"
  sina_redirect_uri: "http://quillme.oopsdata.com:3000/connects/sina"
  qq_app_id: "100271825"
  qq_app_key: "31d510c1ce2265b8e38d5ab6dbcea119"
  qq_redirect_uri: "http://quillme.oopsdata.com/connects/qq"
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://quillme.oopsdata.com:3000/connects/google"
  qihu_app_id: "102205843"
  qihu_app_key: "ca6d278b690138f21cf31ea6fd3f6e2e"
  qihu_app_secret: "25e635ca1c06b32ef02f1fbfa996c74d"
  qihu_redirect_uri: "http://test.oopsdata.com/qihu_connect"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"
test:
  words_per_second: 5
  login_count_threshold: 100
  activate_expiration_time: 3600
  password_expiration_time: 3600
  cache_key_prefix: "oopsdata_"
  redis_hostname: "localhost"
  renren_app_id: "194585"
  renren_api_key: "aa0e45712a7a4960af981ea3f6918b86"
  renren_secret_key: "b2490c767d264f848a3ef026aadcace0"
  renren_redirect_uri: "http://test.oopsdata.com/renren_connect"
  sina_app_key: "2963346595"
  sina_app_secret: "cbe13ee9c88aa72f992d45a0f8d7edd7"
  sina_redirect_uri: "http://test.oopsdata.com/sina_connect"
  qq_app_id: "100271825"
  qq_app_key: "31d510c1ce2265b8e38d5ab6dbcea119"
  qq_redirect_uri: "http://test.oopsdata.com/qq_connect"
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://test.oopsdata.com/google_connect"
  qihu_app_id: "102205843"
  qihu_app_key: "ca6d278b690138f21cf31ea6fd3f6e2e"
  qihu_app_secret: "25e635ca1c06b32ef02f1fbfa996c74d"
  qihu_redirect_uri: "http://quill.oopsdata.com/qihu_connect"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"


question_default_settings:
  content: "请在此输入问题标题"
  note: ""

login_keep_time: 86400 # 1.days.to_i
