production:
  words_per_second: 5
  login_count_threshold: 1000
  activate_expiration_time: 86400
  password_expiration_time: 86400
  cache_key_prefix: "oopsdata_"
  redis_hostname: "orange02"
  renren_app_id: "242457"
  renren_api_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_secret_key: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "1101078681"
  tecent_app_secret: "B3WDffIZM3PYlQKh"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"  
  alipay_app_key: "2013101100001739"
  alipay_redirect_uri: "http://wenjuanba.com/connects/alipay"
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://quill.oopsdata.com/qihu_connect"      
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://quill.oopsdata.com/google_connect"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"
  baidu_app_id: "498046"
  baidu_api_key: "STFYxeMfwouPVtMjseFymHGD"
  baidu_api_secret: "G7Q3qF4QLLGcweyxFYiD5901ybgRZ8tk"
  sohu_app_key: "9ab2466b42224c0c9b038e327db61b97"
  sohu_app_secret: "7da1b4966cbc595abeddf75a697011f3"
demo:
  words_per_second: 5
  login_count_threshold: 1000
  activate_expiration_time: 86400
  password_expiration_time: 86400
  cache_key_prefix: "oopsdata_"
  redis_hostname: "orange02"
  renren_app_id: "242457"
  renren_api_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_secret_key: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "100538121"
  tecent_app_secret: "f45e55fbeee751d03e791a4463517724"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"
  alipay_app_key: "2013101100001739"
  alipay_redirect_uri: "http://wenjuanba.com/connects/alipay"  
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://quill.oopsdata.com/qihu_connect"     
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://quill.oopsdata.com/google_connect"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"
  baidu_app_id: "498046"
  baidu_api_key: "STFYxeMfwouPVtMjseFymHGD"
  baidu_api_secret: "G7Q3qF4QLLGcweyxFYiD5901ybgRZ8tk"
  sohu_app_key: "9ab2466b42224c0c9b038e327db61b97"
  sohu_app_secret: "7da1b4966cbc595abeddf75a697011f3"
staging:
  words_per_second: 5
  login_count_threshold: 1000
  activate_expiration_time: 86400
  password_expiration_time: 86400
  cache_key_prefix: "oopsdata_"
  redis_hostname: "orange02"
  renren_app_id: "242457"
  renren_api_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_secret_key: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "1101078681"
  tecent_app_secret: "B3WDffIZM3PYlQKh"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"
  alipay_app_key: "2013101100001739"
  alipay_redirect_uri: "http://wenjuanba.com/connects/alipay"
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://quill.oopsdata.com/qihu_connect"    
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://quill.oopsdata.com/google_connect"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"
  baidu_app_id: "498046"
  baidu_api_key: "STFYxeMfwouPVtMjseFymHGD"
  baidu_api_secret: "G7Q3qF4QLLGcweyxFYiD5901ybgRZ8tk"
  sohu_app_key: "9ab2466b42224c0c9b038e327db61b97"
  sohu_app_secret: "7da1b4966cbc595abeddf75a697011f3"
development:
  words_per_second: 5
  login_count_threshold: 100
  activate_expiration_time: 3600
  password_expiration_time: 3600
  cache_key_prefix: "oopsdata_"
  redis_hostname: "localhost"
  renren_app_id: "242457"
  renren_app_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_app_secret: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://www.wenjuanba.com/connects/sina"
  qq_app_key: "100538121"
  qq_app_secret: "f45e55fbeee751d03e791a4463517724"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "801426466"
  tecent_app_secret: "bc29ec016529bb4085689d378c3979be"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"
  alipay_app_key: "2013101100001739"
  alipay_redirect_uri: "http://wenjuanba.com/connects/alipay"  
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://test.oopsdata.com/qihu_connect"    
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://quillme.oopsdata.com:3000/connects/google"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"
  baidu_app_id: "498046"
  baidu_api_key: "STFYxeMfwouPVtMjseFymHGD"
  baidu_api_secret: "G7Q3qF4QLLGcweyxFYiD5901ybgRZ8tk"
  sohu_app_key: "9ab2466b42224c0c9b038e327db61b97"
  sohu_app_secret: "7da1b4966cbc595abeddf75a697011f3"
test:
  words_per_second: 5
  login_count_threshold: 100000
  activate_expiration_time: 3600
  password_expiration_time: 3600
  cache_key_prefix: "oopsdata_"
  redis_hostname: "localhost"
  renren_app_id: "242457"
  renren_api_key: "7ed6ca0837d44dffb530db1fc66142ac"
  renren_secret_key: "f53f9a475c2c4de8a6cad3ab11d07265"
  renren_redirect_uri: "http://wenjuanba.com/connects/renren"
  sina_app_key: "851453860"
  sina_app_secret: "c10a578ba8926c3087f6fe04bc2349f1"
  sina_redirect_uri: "http://wenjuanba.com/connects/sina"
  qq_app_key: "1101078681"
  qq_app_secret: "B3WDffIZM3PYlQKh"
  qq_redirect_uri: "http://wenjuanba.com/connects/qq"
  tecent_app_key: "1101078681"
  tecent_app_secret: "B3WDffIZM3PYlQKh"
  tecent_redirect_uri: "http://wenjuanba.com/connects/tecent"  
  alipay_app_key: "2013101100001739"
  alipay_redirect_uri: "http://wenjuanba.com/connects/alipay"   
  google_client_id: "36926710043.apps.googleusercontent.com"
  google_client_secret: "pi235pau5iP7IcAlDqxOz2bz"
  google_redirect_uri: "http://test.oopsdata.com/google_connect"
  qihu_app_id: "10425"
  qihu_app_key: "c83cf3b2688f4f1c695bc9906a2dcf14"
  qihu_app_secret: "5822aa2a51c9d34b61a8b51217eacac4"
  qihu_redirect_uri: "http://quill.oopsdata.com/qihu_connect"
  kaixin_app_id: "100046692"
  kaixin_api_key: "173805652095b523553bc42aa44f8171"
  kaixin_secret_key: "8cca39b07135cf667b162aefd6a7e616"
  douban_api_key: "06b0041f88738b9e14100c5e995aa2da"
  douban_secret_key: "5739d694a7c3d5ff"
  baidu_app_id: "498046"
  baidu_api_key: "STFYxeMfwouPVtMjseFymHGD"
  baidu_api_secret: "G7Q3qF4QLLGcweyxFYiD5901ybgRZ8tk"
  sohu_app_key: "9ab2466b42224c0c9b038e327db61b97"
  sohu_app_secret: "7da1b4966cbc595abeddf75a697011f3"


question_default_settings:
  content: "请在此输入问题标题"
  note: ""

login_keep_time: 86400 # 1.days.to_i
