---
default:
  appid: wx686aaf7a6275c875
  secret: 440490022d47d6907d857c6968f2e291
  token: wenjuanba2015wecharts
  redirect_uri: http://staging.wenjuanba.com/wecharts/wechart_auth
production:
  appid: wx686aaf7a6275c875
  secret: 440490022d47d6907d857c6968f2e291
  token: wenjuanba2015wecharts
  redirect_uri: http://staging.wenjuanba.com/wecharts/wechart_auth
staging:
  appid: wx686aaf7a6275c875
  secret: 440490022d47d6907d857c6968f2e291
  token: wenjuanba2015wecharts
  redirect_uri: http://staging.wenjuanba.com/wecharts/wechart_auth
development:
  appid: wx686aaf7a6275c875
  secret: 440490022d47d6907d857c6968f2e291
  token: wenjuanba2015wecharts
  redirect_uri: http://staging.wenjuanba.com/wecharts/wechart_auth
